CREATE TABLE IF NOT EXISTS MENU_GROUP (id IDENTITY PRIMARY KEY, name TEXT)

CREATE TABLE IF NOT EXISTS PRODUCT (id IDENTITY PRIMARY KEY, name TEXT, price DECIMAL, UNIQUE (id))

CREATE TABLE IF NOT EXISTS ORDER_TABLE(id IDENTITY PRIMARY KEY, number_of_guests INTEGER , empty BOOLEAN)
CREATE TABLE IF NOT EXISTS ORDER_TABLE_REF(table_group_id INTEGER, order_table_id INTEGER )

CREATE TABLE IF NOT EXISTS TABLE_GROUP(id IDENTITY PRIMARY KEY, order_table_id INTEGER, created_date TIMESTAMP)