CREATE TABLE IF NOT EXISTS MENU_GROUP (id IDENTITY PRIMARY KEY, name TEXT)

CREATE TABLE IF NOT EXISTS PRODUCT (id IDENTITY PRIMARY KEY, name TEXT, price DECIMAL, UNIQUE (id))

CREATE TABLE IF NOT EXISTS ORDER_TABLE(id IDENTITY PRIMARY KEY, number_of_guests INTEGER , empty BOOLEAN)
CREATE TABLE IF NOT EXISTS ORDER_TABLE_REF(table_group_id BIGINT, order_table_id BIGINT )

CREATE TABLE IF NOT EXISTS TABLE_GROUP(id IDENTITY PRIMARY KEY, order_table_id INTEGER, created_date TIMESTAMP)

CREATE TABLE IF NOT EXISTS ORDERS(id IDENTITY PRIMARY KEY, order_status TEXT, ordered_time TIMESTAMP)
CREATE TABLE IF NOT EXISTS ORDERS_ORDER_TABLE_REF(orders_id BIGINT, order_table_id BIGINT)

CREATE TABLE IF NOT EXISTS ORDER_LINE_ITEM(seq IDENTITY PRIMARY KEY, quantity INTEGER)
CREATE TABLE IF NOT EXISTS MENU_REF(orders_line_item_seq BIGINT, menu_id BIGINT)

CREATE TABLE IF NOT EXISTS MENU(id IDENTITY PRIMARY KEY, name TEXT, price DECIMAL, menu_group_id BIGINT)
CREATE TABLE IF NOT EXISTS MENU_PRODUCT(menu_id BIGINT, seq IDENTITY PRIMARY KEY, product_id BIGINT, quantity BIGINT)